### ISSUE TITLE
Отправка показаний

### ISSUE THREAD

**Issue by ananyevgv** [alryaz/hass-tns-energo#4]
Показания надо отправлять с последней цифры?

alias: Send to Power
description: ''
trigger:
  - platform: time
    at: '14:00'
condition:
  - condition: template
    value_template: |
      {{ now().day == 25 }}
action:
  - service: tns_energo.push_indications
    target:
      entity_id: sensor.tns_yar_1111111111111_meter_11111111
    data:
      indications: sensor.pzem_004t_v3_energy::-1
mode: single

**Comment by alryaz** [comment]
Попробуйте вот так:

```yaml
alias: Send to Power
description: ''
trigger:
  - platform: time
    at: '14:00'
condition:
  - condition: template
    value_template: |
      {{ now().day == 25 }}
action:
  - service: tns_energo.push_indications
    target:
      entity_id: sensor.tns_yar_1111111111111_meter_11111111
    data_template:  # Изменение тут
      indications: {{ states('sensor.pzem_004t_v3_energy') }}  # Изменение тут
mode: single
```

**Comment by alexfrolkin** [comment]
> Напрямую подсовывать `entity_id` источника значений в `indications` нельзя.
> 
> Попробуйте вот так (если я правильно понял запрос):
> 
> ```yaml
> alias: Send to Power
> description: ''
> trigger:
>   - platform: time
>     at: '14:00'
> condition:
>   - condition: template
>     value_template: |
>       {{ now().day == 25 }}
> action:
>   - service: tns_energo.push_indications
>     target:
>       entity_id: sensor.tns_yar_1111111111111_meter_11111111
>     data:
>       indications: {{ states('sensor.pzem_004t_v3_energy') }}  # <----------- Изменение тут
> mode: single
> ```

Добрый день, а как показания второго тарифа записать ? через запитую в этих же фигурных скобках или еще одни открывать ?

**Comment by ananyevgv** [comment]
Все получилось
data:
      notification: true
      indications: '{{ states(''sensor.pzem_004t_v3_energy'') }}'
mode: single

**Comment by chex01** [comment]
> 
> Добрый день, а как показания второго тарифа записать ? 

В описании компонента куча замечательных примеров...можно например так:
```
    data:
      indications:
        t1: {{ states('sensor.energy_den') | round(0) }}
        t2: {{ states('sensor.energy_noch') | round(0) }}
```
> 
> И подскажите, пожалуйста, как округлить значения если у меня после запятой еще три знака ?

Для округления используйте: round(0)
